poppy:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------

  m1_position_controller:
    type: effort_controllers/JointPositionController
    joint: m1
    pid: {p: 100.0, i: 0.1, d: 10}

  m2_position_controller:
    type: effort_controllers/JointPositionController
    joint: m2
    pid: {p: 100.0, i: 0.1, d: 10}

  m3_position_controller:
    type: effort_controllers/JointPositionController
    joint: m3
    pid: {p: 100.0, i: 0.1, d: 10}

  m4_position_controller:
    type: effort_controllers/JointPositionController
    joint: m4
    pid: {p: 100.0, i: 0.1, d: 10}

  m5_position_controller:
    type: effort_controllers/JointPositionController
    joint: m5
    pid: {p: 100.0, i: 0.1, d: 10}

  m6_position_controller:
    type: effort_controllers/JointPositionController
    joint: m6
    pid: {p: 100.0, i: 0.1, d: 10}

